<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Pet;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::create([
            'name' => 'Admin User',
            'email' => 'admin@pawsome.com',
            'password' => Hash::make('password'),
            'role' => 'admin',
            'phone' => '09171234567',
            'address' => 'Dagupan City, Pangasinan',
        ]);

        User::create([
            'name' => 'Lebron Jaime',
            'email' => 'lebron@test.com',
            'password' => Hash::make('password'),
            'role' => 'adopter',
            'phone' => '09281234567',
            'address' => 'Dagupan City, Pangasinan',
        ]);

        User::create([
            'name' => 'Josephine Cruz',
            'email' => 'josephine@test.com',
            'password' => Hash::make('password'),
            'role' => 'adopter',
            'phone' => '09351234567',
            'address' => 'Lingayen, Pangasinan',
        ]);

        $pets = [
            [
                'name' => 'Buddy',
                'species' => 'dog',
                'breed' => 'Labrador Mix',
                'age_group' => 'young',
                'age_months' => 14,
                'gender' => 'male',
                'size' => 'large',
                'description' => 'Friendly and energetic pup who loves playing fetch. Great with children and other dogs.',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Luna',
                'species' => 'cat',
                'breed' => 'Tabby',
                'age_group' => 'adult',
                'age_months' => 36,
                'gender' => 'female',
                'size' => 'small',
                'description' => 'Calm indoor kitty who loves cozy laps and quiet afternoons by the window.',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_housetrained' => true,
                'good_with_kids' => false,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Milo',
                'species' => 'dog',
                'breed' => 'Beagle Mix',
                'age_group' => 'adult',
                'age_months' => 30,
                'gender' => 'male',
                'size' => 'medium',
                'description' => 'Loves sniffing trails and making new friends on walks. Very gentle and loyal.',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Pip',
                'species' => 'small_pet',
                'breed' => 'Guinea Pig',
                'age_group' => 'baby',
                'age_months' => 3,
                'gender' => 'male',
                'size' => 'small',
                'description' => 'Tiny, curious, and irresistibly fluffy. Perfect for first-time pet owners.',
                'is_vaccinated' => false,
                'is_neutered' => false,
                'is_housetrained' => false,
                'good_with_kids' => true,
                'good_with_pets' => false,
                'status' => 'available',
            ],
            [
                'name' => 'Coco',
                'species' => 'dog',
                'breed' => 'Aspin',
                'age_group' => 'young',
                'age_months' => 18,
                'gender' => 'female',
                'size' => 'medium',
                'description' => 'Sweet and playful rescued dog. She loves cuddles and is very food motivated.',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => false,
                'status' => 'available',
            ],
            [
                'name' => 'Nala',
                'species' => 'cat',
                'breed' => 'Persian Mix',
                'age_group' => 'young',
                'age_months' => 12,
                'gender' => 'female',
                'size' => 'small',
                'description' => 'Fluffy and affectionate. Nala loves being brushed and sitting on laps.',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Dan',
                'species' => 'dog',
                'breed' => 'Tiger Commando',
                'age_group' => 'adult',
                'age_months' => 48,
                'gender' => 'male',
                'size' => 'large',
                'description' => 'Loyal, intelligent, and protective. Dan needs an experienced owner with a yard.',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_housetrained' => true,
                'good_with_kids' => false,
                'good_with_pets' => false,
                'status' => 'available',
            ],
            [
                'name' => 'Whiskers',
                'species' => 'small_pet',
                'breed' => 'Hamster',
                'age_group' => 'baby',
                'age_months' => 2,
                'gender' => 'female',
                'size' => 'small',
                'description' => 'Tiny and adorable. Whiskers is very active at night and loves running on her wheel.',
                'is_vaccinated' => false,
                'is_neutered' => false,
                'is_housetrained' => false,
                'good_with_kids' => true,
                'good_with_pets' => false,
                'status' => 'available',
            ],
            [
                'name' => 'Rocky',
                'species' => 'dog',
                'breed' => 'Shih Tzu Mix',
                'age_group' => 'senior',
                'age_months' => 84,
                'gender' => 'male',
                'size' => 'small',
                'description' => 'Gentle senior dog looking for a quiet loving home. Low energy but full of love.',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Bella',
                'species' => 'cat',
                'breed' => 'Domestic Shorthair',
                'age_group' => 'adult',
                'age_months' => 24,
                'gender' => 'female',
                'size' => 'medium',
                'description' => 'Independent but loving. Bella enjoys her alone time but always comes back for cuddles.',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => false,
                'status' => 'available',
            ],
            [
                'name' => 'Tutoy',
                'species' => 'dog',
                'breed' => 'Poodle Mix',
                'age_group' => 'young',
                'age_months' => 10,
                'gender' => 'male',
                'size' => 'small',
                'description' => 'Playful and smart. Tutoy learns tricks quickly and loves being the center of attention.',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Hazel',
                'species' => 'cat',
                'breed' => 'Siamese Mix',
                'age_group' => 'young',
                'age_months' => 8,
                'gender' => 'female',
                'size' => 'small',
                'description' => 'Talkative and curious. Hazel will follow you around the house and chat all day.',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Bruno',
                'species' => 'dog',
                'breed' => 'Bulldog Mix',
                'age_group' => 'adult',
                'age_months' => 42,
                'gender' => 'male',
                'size' => 'large',
                'description' => 'Calm and easygoing. Bruno is a couch potato who loves naps and belly rubs.',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Daisy',
                'species' => 'small_pet',
                'breed' => 'Rabbit',
                'age_group' => 'young',
                'age_months' => 6,
                'gender' => 'female',
                'size' => 'small',
                'description' => 'Soft and gentle. Daisy loves fresh vegetables and hopping around the garden.',
                'is_vaccinated' => false,
                'is_neutered' => false,
                'is_housetrained' => false,
                'good_with_kids' => true,
                'good_with_pets' => false,
                'status' => 'available',
            ],
            [
                'name' => 'Kiko',
                'species' => 'dog',
                'breed' => 'Aspin',
                'age_group' => 'baby',
                'age_months' => 4,
                'gender' => 'male',
                'size' => 'small',
                'description' => 'A tiny bundle of joy rescued from the streets. Kiko is brave, curious, and full of life.',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_housetrained' => false,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Mocha',
                'species' => 'cat',
                'breed' => 'Domestic Longhair',
                'age_group' => 'adult',
                'age_months' => 28,
                'gender' => 'female',
                'size' => 'medium',
                'description' => 'Sweet and gentle. Mocha loves warm spots by the window and slow mornings.',
                'is_vaccinated' => true,
                'is_neutered' => true,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Rex',
                'species' => 'dog',
                'breed' => 'Labrador Mix',
                'age_group' => 'young',
                'age_months' => 16,
                'gender' => 'male',
                'size' => 'large',
                'description' => 'High energy and loves the outdoors. Rex is great for active families.',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Pepper',
                'species' => 'small_pet',
                'breed' => 'Guinea Pig',
                'age_group' => 'young',
                'age_months' => 5,
                'gender' => 'male',
                'size' => 'small',
                'description' => 'Pepper is social and loves being held. He squeaks happily when he sees vegetables.',
                'is_vaccinated' => false,
                'is_neutered' => false,
                'is_housetrained' => false,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Ginger',
                'species' => 'cat',
                'breed' => 'Orange Tabby',
                'age_group' => 'baby',
                'age_months' => 3,
                'gender' => 'male',
                'size' => 'small',
                'description' => 'A feisty little ginger kitten with tons of personality. Loves playing with strings.',
                'is_vaccinated' => false,
                'is_neutered' => false,
                'is_housetrained' => false,
                'good_with_kids' => true,
                'good_with_pets' => true,
                'status' => 'available',
            ],
            [
                'name' => 'Atlas',
                'species' => 'dog',
                'breed' => 'Husky Mix',
                'age_group' => 'young',
                'age_months' => 20,
                'gender' => 'male',
                'size' => 'large',
                'description' => 'Majestic and full of energy. Atlas loves the cold and needs lots of exercise.',
                'is_vaccinated' => true,
                'is_neutered' => false,
                'is_housetrained' => true,
                'good_with_kids' => true,
                'good_with_pets' => false,
                'status' => 'available',
            ],
        ];

        foreach ($pets as $pet) {
            Pet::create($pet);
        }
    }
}